### ISSUE TITLE
nobo bobos using old version

### ISSUE THREAD

**Issue by ghost** [chillerbot/chillerbot-ux#123]
create new github release :d 
also would a nightly build be possible?

**Comment by ChillerDragon** [comment]
There is basically a nightly build from microsoft. Every commit will be built in the pipeline and can be downloaded here:

![image](https://user-images.githubusercontent.com/20344300/208529066-7f70b8bf-64e4-4187-9a2a-6a7bb7f68ab4.png)
![image](https://user-images.githubusercontent.com/20344300/208529319-73620402-957b-4aed-a3b3-319969501d68.png)

I am aware that it has been a while since the last release. Its just some features are way too work in progress for a proper release. Like for example playtime tracking and the warlist. And im too lazy to finish those.
