### ISSUE TITLE
silent chat commands?

### ISSUE THREAD

**Issue by qxdFox** [chillerbot/chillerbot-ux#166]
could you please add a silent chat command option? or make a certain prefix not send a message in chat? i would really love to see that!
have a great day

**Comment by ChillerDragon** [comment]
Originally I used the chat because it was the easiest way to get user input. And I did not hide them because it did not seem like it is worth the effort to maintain that code. But checking it again it is not that bad.

Anyways you are totally right there should be such a feature and I added it now ``cl_silent_chat_commands 1`` will not send known chat commands to the server anymore. But if you do a typo it will be sent.

I decided to leave the default like it was before. Because it turned out those chat commands are actually good marketing for the client haha.

I rarely do new releases of the client. So if you need that feature and do not want to wait a year for a new release I recommend building the client from source. Alternatively you can also download the pre built binaries from the github actions. They are at the bottom of this page https://github.com/chillerbot/chillerbot-ux/actions/runs/11305412133

[![dl](https://github.com/user-attachments/assets/0f7af69f-1d6d-43dc-a2c4-1ef74651b817)](https://github.com/chillerbot/chillerbot-ux/actions/runs/11305412133)

**Comment by qxdFox** [comment]
hello, I think updating the warlist stuff broke something

when using /team for example it actually adds that team number as a team in the names.txt
I think it should be a simple fix by removing the "/" from that one File i forgot

and a quick question, is the camp thing banable?

**Comment by ChillerDragon** [comment]
> when using /team for example it actually adds that team number as a team in the names.txt

Nice thanks for reporting. It should be fixed now.

> is the camp thing banable?

Yes but it depends on the server. DDNet for example prohibits automated inputs so it would technically be illegal there. I use it there sometimes when I go afk in a race to not get dragged into the next part. So far I have not been banned for it. I mostly use it on block servers but then only after asking the admins for permission.

**Comment by qxdFox** [comment]
Hello, it's me once again, seems like my silent chat commande request broke alot more..
Don't know if that's a good thing or a bad thing but I've noticed that the reading of names in chat commands is kinda broken.
For example when I type "!addwar " and auto complete a name, it will say "!addwar Name " with a space at the end.
I dont know if that was always like this but it doesnt add the right name to the warlist, instead it adds "Name " and not "Name" which is very annoying..
Hope you will be able to fix this and that this will be the last time I have to annoy you :p

**Comment by ChillerDragon** [comment]
Thanks fixed. Artifacts will appear here: https://github.com/chillerbot/chillerbot-ux/actions/runs/11422902147
